# variable "compartment_id" {}
# variable "fnc_app_display_name" {}
# variable "fnc_display_name" {}
# variable "fnc_memory_in_mbs" {}
# variable "fnc_subnet_app_cidr" {}
# variable "fnc_subnet_app_display_name" {}
# variable "fnc_subnet_app_dns_label" {}
# variable "fnc_app_rt_display_name" {}
# variable "fnc_app_sl_display_name" {}
# variable "fnc_ocir_docker_repository" {}
# variable "fnc_ocir_repo_name" {}
# variable "fnc_ocir_user_name" {}
# variable "fnc_ocir_user_password" {}
# variable "fnc_ocir_namespace" {}
# variable "service_cidr_block" {}
# variable "vcn_id" {}
# variable "vcn_default_dhcp_options_id" {}
# variable "sg_id" {}
# variable "ng_id" {}